# Model Architecture
model:
  type: "dbm"  # Options: dbm, conditional_dbm, conv_dbm
  hidden_dims: [500, 500]  # Hidden layer dimensions
  visible_dim: 784  # For MNIST (28x28)
  dropout_rate: 0.2
  batch_norm: true

# Training
training:
  batch_size: 128
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 1e-4
  epochs: 100
  early_stopping_patience: 10
  cd_steps: 1  # Contrastive divergence steps

# Sampling
sampling:
  num_samples: 100
  num_steps: 1000
  temperature: 1.0

# Data
data:
  dataset: "mnist"  # Options: mnist, fashion_mnist
  train_val_split: 0.9
  normalize: true
  augmentation: false

# Logging
logging:
  log_dir: "results/logs"
  save_dir: "models/checkpoints"
  tensorboard: true
  log_interval: 100
  save_interval: 1000

# Hardware
hardware:
  device: "cuda"  # Options: cuda, cpu
  num_workers: 4
  pin_memory: true 